name: Central CI - All Repositories

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Repositories to test (comma-separated or "all")'
        required: true
        default: 'all'
        type: string
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - all
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

env:
  # Repository configurations
  SIT_TO_STAND_REPO: 'sit-to-stand-planner'
  ISAAC_SIM_NAV_REPO: 'isaac_sim_nav'

jobs:
  determine-repos:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.parse.outputs.repositories }}
    steps:
    - name: Parse repository input
      id: parse
      run: |
        if [[ "${{ github.event.inputs.repositories }}" == "all" || "${{ github.event_name }}" == "schedule" ]]; then
          echo "repositories=[\"sit-to-stand-planner\", \"isaac_sim_nav\"]" >> $GITHUB_OUTPUT
        else
          # Convert comma-separated string to JSON array
          repos="${{ github.event.inputs.repositories }}"
          json_array=$(echo "$repos" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
          echo "repositories=$json_array" >> $GITHUB_OUTPUT
        fi

  test-sit-to-stand-planner:
    needs: determine-repos
    if: contains(fromJson(needs.determine-repos.outputs.repositories), 'sit-to-stand-planner')
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning workspace..."
        rm -rf sit-to-stand-planner || true
        docker system prune -f || true
        find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

    - name: Clone sit-to-stand-planner
      run: |
        git clone https://github.com/${{ github.repository_owner }}/sit-to-stand-planner.git
        cd sit-to-stand-planner
        git log --oneline -5

    - name: Build Docker image for sit-to-stand-planner
      working-directory: ./sit-to-stand-planner
      run: |
        echo "Building test environment for sit-to-stand-planner..."
        docker build -t sit-to-stand-test .

    - name: Run sit-to-stand-planner tests
      working-directory: ./sit-to-stand-planner
      run: |
        test_type="${{ github.event.inputs.test_type || 'smoke' }}"
        echo "Running $test_type tests for sit-to-stand-planner..."

        if [[ "$test_type" == "smoke" ]]; then
          docker run --rm \
            --memory=2g \
            --memory-swap=3g \
            --cpus=2 \
            --user $(id -u):$(id -g) \
            -v $(pwd):/workspace \
            sit-to-stand-test \
            bash -c "
              source /opt/ros/humble/setup.bash &&
              ./run_tests.sh smoke
            "
        else
          docker run --rm \
            --memory=4g \
            --memory-swap=6g \
            --cpus=2 \
            --user $(id -u):$(id -g) \
            -v $(pwd):/workspace \
            sit-to-stand-test \
            bash -c "
              source /opt/ros/humble/setup.bash &&
              ./run_tests.sh all &&
              pip install flake8 &&
              flake8 *.py test/*.py --max-line-length=100 --ignore=E203,W503 || true
            "
        fi

    - name: Cleanup sit-to-stand-planner
      if: always()
      run: |
        rm -rf sit-to-stand-planner || true
        docker rmi sit-to-stand-test || true

  test-isaac-sim-nav:
    needs: determine-repos
    if: contains(fromJson(needs.determine-repos.outputs.repositories), 'isaac_sim_nav')
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning workspace..."
        rm -rf isaac_sim_nav || true
        docker system prune -f || true

    - name: Clone isaac_sim_nav
      run: |
        git clone https://github.com/${{ github.repository_owner }}/isaac_sim_nav.git
        cd isaac_sim_nav
        git log --oneline -5

    - name: Setup isaac_sim_nav environment
      working-directory: ./isaac_sim_nav
      run: |
        echo "Setting up isaac_sim_nav environment..."
        # Check if Dockerfile exists, otherwise create a basic test setup
        if [[ -f "Dockerfile" ]]; then
          docker build -t isaac-sim-nav-test .
        elif [[ -f "requirements.txt" ]]; then
          # Create a basic Python environment for testing
          docker run --rm -v $(pwd):/workspace -w /workspace python:3.8-slim bash -c "
            pip install -r requirements.txt &&
            python -m pytest tests/ || python -m unittest discover tests/ || echo 'No standard test framework found'
          "
        else
          echo "No clear build or test configuration found for isaac_sim_nav"
          ls -la
        fi

    - name: Run isaac_sim_nav tests
      working-directory: ./isaac_sim_nav
      run: |
        test_type="${{ github.event.inputs.test_type || 'smoke' }}"
        echo "Running $test_type tests for isaac_sim_nav..."

        # Adapt based on what test infrastructure exists
        if [[ -f "run_tests.sh" ]]; then
          chmod +x run_tests.sh
          ./run_tests.sh $test_type
        elif [[ -f "Dockerfile" ]]; then
          docker run --rm \
            --memory=2g \
            --cpus=2 \
            -v $(pwd):/workspace \
            isaac-sim-nav-test \
            bash -c "echo 'Running isaac_sim_nav tests...' && ls -la"
        else
          echo "Running basic validation for isaac_sim_nav..."
          python -c "import sys; print(f'Python version: {sys.version}')"
          find . -name "*.py" -exec python -m py_compile {} \; || echo "Some Python files have syntax errors"
        fi

    - name: Cleanup isaac_sim_nav
      if: always()
      run: |
        rm -rf isaac_sim_nav || true
        docker rmi isaac-sim-nav-test || true

  report-results:
    needs: [test-sit-to-stand-planner, test-isaac-sim-nav]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Generate test report
      run: |
        echo "## Central CI Test Results" >> $GITHUB_STEP_SUMMARY
        echo "| Repository | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------------|--------|" >> $GITHUB_STEP_SUMMARY

        if [[ "${{ needs.test-sit-to-stand-planner.result }}" == "success" ]]; then
          echo "| sit-to-stand-planner | ✅ PASSED |" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ needs.test-sit-to-stand-planner.result }}" == "failure" ]]; then
          echo "| sit-to-stand-planner | ❌ FAILED |" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ needs.test-sit-to-stand-planner.result }}" == "skipped" ]]; then
          echo "| sit-to-stand-planner | ⏭️ SKIPPED |" >> $GITHUB_STEP_SUMMARY
        fi

        if [[ "${{ needs.test-isaac-sim-nav.result }}" == "success" ]]; then
          echo "| isaac_sim_nav | ✅ PASSED |" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ needs.test-isaac-sim-nav.result }}" == "failure" ]]; then
          echo "| isaac_sim_nav | ❌ FAILED |" >> $GITHUB_STEP_SUMMARY
        elif [[ "${{ needs.test-isaac-sim-nav.result }}" == "skipped" ]]; then
          echo "| isaac_sim_nav | ⏭️ SKIPPED |" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Test type:** ${{ github.event.inputs.test_type || 'smoke' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Timestamp:** $(date -u)" >> $GITHUB_STEP_SUMMARY